# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages0) leave off the trailing slash, e.g. /my-project
# baseurl: "/MarketingCloudSDK-Android" # the subpath of your site, e.g. /blog/

url: "http://salesforce-marketingcloud.github.io" # the base hostname & protocol for your site

# URL to source code, used in _includes/footer.html
codeurl: 'https://github.com/salesforce-marketingcloud/MarketingCloudSDK-Android'

# Site title and subtitle. This is used in _includes/header.html
#
# to create a new page, use this format:
# ruby bin/jekyll-page "name of page" section
#
title: 'SFMCSdk Android'

# Current SDK version, use for all mentions
currentVersion: "8.0.1"

# Current SDK major minor version.  Used to reference javadoc
currentMajorMinor: "8.0"

# Google Play Services Location version for current SDK release
currentGmsLocationVersion: "17.1.0"

# Firebase major version
firebaseCoreMajor: "22"

# AltBeacon version for current SDK release
currentAltBeaconVersion: "2.19"

# Min Android SDK supported by MC SDK
minAndroidSdkVersion: "21"

# Target and compile Android SDK used by MC SDK
compileAndroidSdkVersion: "31"

# Marketing Cloud Delay
propagationDelay: "5 minutes"

# if you use google analytics, add your tracking id here
google_analytics_id: 'G-5JSZM48ZY9' #PROD

# Enable/show navigation. There are there options:
#   0 - always hide
#   1 - always show
#   2 - show only if posts are present
navigation: 1

collections:
  releases:
    permalink: "releases/:path"

# Default categories (in order) to appear in the navigation
sections: [
    ['docs', "Documentation"],
    ['provisioning', 'Provisioning'],
    ['create-apps', 'Create Cloud Apps'],
    ['sdk-implementation', 'SDK Implementation'],
    ['notifications', 'Notifications'],
    ['in-app-message', 'In-App Messaging'],
    ['inbox', 'Inbox Messaging'],
    ['location', 'Location Messaging'],
    ['analytics', 'Analytics'],
    ['use-cases', 'Use Cases'],
    ['trouble-shooting', 'Troubleshooting']
]

# Dates are not included in permalinks
permalink: none

# Syntax highlighting
highlighter: rouge

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: ['bin', 'README.md', 'docker-compose.yml']

# Use the kramdown Markdown renderer
markdown: kramdown
